### ISSUE TITLE
Module config

### ISSUE THREAD

**Issue by rtwent** [dmstr/yii2-news-module#2]
Thank You for the list of wonderfull modules.
I think this module is an exception. I'll not recomend to install it.
1. Absence of configuration files, to find routes I have to search in vendor directory.
2. Not correct dependencies. When the problems with routes were solved, i've got an exception that https://github.com/dmstr/yii2-bootstrap is absent.
3. When I fixed an exception with bootsrap-tabs, I've got an exception with not correct path to views files.
4. Readme is very poor.
That was enough for me, my current version of yii advanced is 2.0.8.

Best regards and thank You very much for Your other projects!!!

**Comment by schmunk42** [comment]
You're absolutely right, sorry about that. Thanks for your open words.

@Quexer69 Shall we drop this extension?

**Comment by artmart** [comment]
Will you help me to install it?
Can you put some additional details about the configurations?

Thanks.

**Comment by Quexer69** [comment]
Sorry for the late response but we do not use / maintain this project anymore.

We will remove this at the end of the week. If you still using it, plz make a fork.
